name: my_ios_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.3.1
  provider: ^4.3.2+3

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/shop/1.png
    - assets/shop/2.png
    - assets/shop/3.png
    - assets/shop/4.png
    - assets/shop/5.png
    - assets/shop/6.png
    - assets/shop/triangleProduct1.png
    - assets/shop/triangleProduct2.png
    - assets/shop/triangleProduct3.png
    - assets/shop/triangleProduct4.png
    - assets/shop/polygon1.png
    - assets/shop/polygon2.png
    - assets/shop/polygon3.png
    - assets/shop/polygon4.png
    - assets/shop/acceptance.png
    - assets/wallet/earth.png
    - assets/wallet/card.png
    - assets/wallet/card_two.png
    - assets/shopping_action.png
    - assets/wallet_action.png
    - assets/wallet/add_card_promo.png


