name: my_ios_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.3.1

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/album.jpeg
    - assets/shop/logo.png
    - assets/shop/1.png
    - assets/shop/2.png
    - assets/shop/3.png
    - assets/shop/4.png
    - assets/shop/5.png
    - assets/shop/6.png
    - assets/shop/triangleProduct1.png
    - assets/shop/triangleProduct2.png
    - assets/shop/triangleProduct3.png
    - assets/shop/triangleProduct4.png
    - assets/shop/acceptance.png
    - assets/wallet/acceptanceMark.png
    - assets/wallet/money.png
    - assets/wallet/card.png
    - assets/music_action.png
    - assets/shopping_action.png
    - assets/wallet_action.png


